name: build and release
on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

  strategy:
    matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: prepare node environment
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: build/release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # release on commit with message "vx.x.x" ( ie v1.0.0 )
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: compile

          #Base64-encoded code signing certificate for macOS
          mac_certs: ${{ secrets.MAC_CERTS }}
          mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
